"""empty message

Revision ID: 2477c7bed596
Revises: d67e8a078d52
Create Date: 2024-02-22 16:27:31.507471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2477c7bed596'
down_revision = 'd67e8a078d52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pro', schema=None) as batch_op:
        batch_op.drop_constraint('uq_username', type_='unique')
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pro', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=100), nullable=True))
        batch_op.create_unique_constraint('uq_username', ['username'])

    # ### end Alembic commands ###
