"""empty message

Revision ID: d67e8a078d52
Revises: 4f3be50accbe
Create Date: 2024-02-22 15:59:24.556364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd67e8a078d52'
down_revision = '4f3be50accbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pro') as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=100), nullable=True))
        batch_op.create_unique_constraint('uq_username', ['username'])

    # ### end Alembic commands ###


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pro', schema='milano') as batch_op:
        batch_op.drop_constraint('milano', type_='unique')
        batch_op.drop_column('username')

    # ### end Alembic commands ###
